<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Produtos\GetProduto\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Mediator.Abstractions" Version="3.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InventarioComercial.Domain\InventarioComercial.Domain.csproj" />
    <ProjectReference Include="..\InventarioComercial.Infrastructure\InventarioComercial.Infrastructure.csproj" />
  </ItemGroup>

</Project>
